name: Rector

on:
  push:
    paths:
      - '**.php'
      - 'rector.php'
      - '.github/workflows/phpstan.yml'

jobs:
  rector:
    name: rector
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run Rector
        run: ./vendor/bin/rector process --dry-run
